---
- name: Kubernetes Setup Playbook
  hosts: localhost
  become: true
  tasks:
    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0755'

    - name: Check if admin.conf exists in .kube/config 
      stat: 
        path: /home/ubuntu/.kube/config 
      register: admin_conf_stat

    - name: Copy admin.conf to .kube/config
      command: sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
      when: not admin_conf_stat.stat.exists

    - name: Change ownership of .kube/config
      file:
        path: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply Flannel CNI
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      become_user: ubuntu