---
- name: Master Config Playbook 
  hosts: localhost 
  become: true 
  tasks:
   - name: Copy installation script to remote host
     copy:
      src: /home/ubuntu/masterinstallation_script.sh
      dest: /tmp/installation_script.sh
      mode: '0755'

   - name: Execute the installation script
     command: /tmp/installation_script.sh

   - name: Run additional command and register output
     command: sudo kubeadm init --apiserver-advertise-address={privateIp} --pod-network-cidr=10.244.0.0/16
     register: command_output

   - name: Save command output to a file
     copy:
       content: "{{ command_output.stdout }}"
       dest: /tmp/command_output.txt

   - name: Fetch the command output to master server
     fetch:
       src: /tmp/command_output.txt
       dest: /home/ubuntu/
       flat: yes

